---
run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - goimports
    - govet
    - staticcheck
    - revive
    - whitespace
    - gofumpt
    - gosimple
    - dupl
    - dupword
    - durationcheck
    - goconst
    - godot
    - gosec
    - sqlclosecheck
    - tagalign
    - mnd
    - godox
    - gocritic
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - unparam
    - lll
    - misspell
    - ineffassign
    - noctx
    - gocyclo


linters-settings:
  gofumpt:
    module-path: github.com/vamage/baconator
    extra-rules: false
  mnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
issues:
  # Disable max issues per linter.
  max-issues-per-linter: 0
  # Disable max same issues.
  max-same-issues: 0
  # Exclude default linters.
  exclude-use-default: false
  exclude:
    - unused-parameter
    - line contains TODO/BUG/FIXME
    - var-naming
  exclude-dirs:
    - api
    - backstage
    - baconator/sql
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec