run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - goimports
    - govet
    - staticcheck
    - revive
    - whitespace
    - gofumpt
    - gosimple
    - dupl
    - dupword
    - durationcheck
    - goconst
    - godot
    - sqlclosecheck
    - tagalign
    - mnd
    - godox
    - gocritic
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - unparam
    - lll
    - misspell
    - ineffassign
    - noctx
    - gocyclo

linters-settings:
  gofumpt:
  mnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'


issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0