volumes:
    postgres_data: {}
services:
  baconator:
    image: baconator
    restart: always
    build:
        context: .
        dockerfile: docker/baconator.Dockerfile
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgresql://postgres:example@db/postgres
  backstage:
    image: backstage
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: backstage2
      LOG_LEVEL: debug
    build:
        context: backstage
        dockerfile: Dockerfile
    ports:
      - "7007:7007"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
