// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package user

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          int64
	Name        string
	DisplayName pgtype.Text
	Email       pgtype.Text
	Picture     pgtype.Text
	Uuid        pgtype.UUID
	Title       pgtype.Text
	Description pgtype.Text
	Labels      []string
	Annotations []string
	Tags        []string
	LinksID     []int32
	CreatedAt   pgtype.Timestamptz
}
