// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// WhoamiGet implements GET /whoami operation.
//
// Return user from oauth token.
//
// GET /whoami
func (UnimplementedHandler) WhoamiGet(ctx context.Context) (r WhoamiGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
