// Code generated by ogen, DO NOT EDIT.

package api

type OAuth2 struct {
	Token  string
	Scopes []string
}

// GetToken returns the value of Token.
func (s *OAuth2) GetToken() string {
	return s.Token
}

// GetScopes returns the value of Scopes.
func (s *OAuth2) GetScopes() []string {
	return s.Scopes
}

// SetToken sets the value of Token.
func (s *OAuth2) SetToken(val string) {
	s.Token = val
}

// SetScopes sets the value of Scopes.
func (s *OAuth2) SetScopes(val []string) {
	s.Scopes = val
}

// Ref: #/components/schemas/User
type User struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

func (*User) whoamiGetRes() {}

// WhoamiGetForbidden is response for WhoamiGet operation.
type WhoamiGetForbidden struct{}

func (*WhoamiGetForbidden) whoamiGetRes() {}
