// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ResourcesPost implements POST /resources operation.
	//
	// Add a new resource type.
	//
	// POST /resources
	ResourcesPost(ctx context.Context, req *Resource) (*Resource, error)
	// ResourcesResourceIdGet implements GET /resources/{resourceId} operation.
	//
	// Return resources.
	//
	// GET /resources/{resourceId}
	ResourcesResourceIdGet(ctx context.Context, params ResourcesResourceIdGetParams) (*Resource, error)
	// WhoamiGet implements GET /whoami operation.
	//
	// Return user from oauth token.
	//
	// GET /whoami
	WhoamiGet(ctx context.Context) (*User, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
